// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DemoAPIEB.Models
{
    public partial class DemoDataListContext : DbContext
    {
        public DemoDataListContext()
        {
        }

        public DemoDataListContext(DbContextOptions<DemoDataListContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DemoDatum> DemoData { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DemoDatum>(entity =>
            {
                entity.HasKey(e => new { e.資料年月, e.公司代號 })
                    .HasName("PK_DemoData_1");

                entity.HasIndex(e => e.產業別, "IDX_產業別");

                entity.Property(e => e.備註).HasMaxLength(100);

                entity.Property(e => e.公司名稱).IsRequired();

                entity.Property(e => e.營業收入上月比較增減).HasColumnName("營業收入_上月比較增減");

                entity.Property(e => e.營業收入上月營收).HasColumnName("營業收入_上月營收");

                entity.Property(e => e.營業收入去年同月增減).HasColumnName("營業收入_去年同月增減");

                entity.Property(e => e.營業收入去年當月營收).HasColumnName("營業收入_去年當月營收");

                entity.Property(e => e.營業收入當月營收).HasColumnName("營業收入_當月營收");

                entity.Property(e => e.產業別)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.累計營業收入前期比較增減).HasColumnName("累計營業收入_前期比較增減");

                entity.Property(e => e.累計營業收入去年累計營收).HasColumnName("累計營業收入_去年累計營收");

                entity.Property(e => e.累計營業收入當月累計營收).HasColumnName("累計營業收入_當月累計營收");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}