// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DemoAPIEB.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DemoAPIEB.Models
{
    public partial interface IDemoDataListContextProcedures
    {
        Task<int> usp_InsertDemoDataAsync(int? 出表日期, int? 資料年月, int? 公司代號, string 公司名稱, string 產業別, int? 營業收入_當月營收, int? 營業收入_上月營收, int? 營業收入_去年當月營收, double? 營業收入_上月比較增減, int? 營業收入_去年同月增減, int? 累計營業收入_當月累計營收, int? 累計營業收入_去年累計營收, double? 累計營業收入_前期比較增減, string 備註, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_SelectByCompanyCodeResult>> usp_SelectByCompanyCodeAsync(int? 公司代號, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
